name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and push Docker image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
          AWS_IP: ${{ secrets.AWS_IP }}
          AWS_USER: ${{ secrets.AWS_USER }}
        run: |
          docker build -t app:bestview .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker tag app:bestview $DOCKER_USER/app:bestview
          docker push $DOCKER_USER/app:bestview

      - name: Deploy to AWS EC2
        env:
          AWS_IP: ${{ secrets.AWS_IP }}
          AWS_USER: ${{ secrets.AWS_USER }}
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          AWS_PEM_FILE: ${{ secrets.AWS_PEM_FILE }}
        run: |
          # Create a temporary file for the PEM key
          echo "$AWS_PEM_FILE" > /tmp/aws_key.pem
          chmod 600 /tmp/aws_key.pem

          # Run SSH commands
          ssh -o StrictHostKeyChecking=no -i /tmp/aws_key.pem $AWS_USER@$AWS_IP << 'EOF'
            docker pull $DOCKER_USER/app:bestview
            docker-compose down
            docker-compose up -d
            docker-compose exec app python manage.py collectstatic --noinput
            docker-compose exec app python manage.py migrate
          EOF
